### ISSUE TITLE
RAD_Surface type contract has duplicates and cannot be completed

### ISSUE THREAD

**Issue by splatpope** [Morphisor244/Research-Advancement-Division#2]
Description : Upon completing all the subjects in a contract defined by RAD_Surface.cfg, the core parameter (of type CollectScience) does not get fulfilled and the contract cannot be completed.
Additionally, the contract contains can contain many duplicates.

Contract before:
![image](https://github.com/user-attachments/assets/d637a769-641a-4a23-8373-e187576e4a44)

Contract after:
![image](https://github.com/user-attachments/assets/3e80d7ed-2951-44fd-a249-4b3e3e39fc1e)

Modlist : 
[splatpope_ksp_list_20241201.txt](https://github.com/user-attachments/files/17968250/splatpope_ksp_list_20241201.txt)

I have no idea how to debug this or else I'd help :p

**Comment by Morphisor244** [comment]
Looks like you're not actually splashed down (in the right place), which the contract specifies. Notice how that requirement is not checked off.

**Comment by splatpope** [comment]
> Looks like you're not actually splashed down (in the right place), which the contract specifies. Notice how that requirement is not checked off.

Yeah, but that picture was taken at the KSC after recovering the craft; every line but the CollectScience parameter is green right before recovery

All those science subjects were ticked green after the corresponding experiment was done splashed down at Kerbin's Shores, as required

**Comment by Morphisor244** [comment]
If that's the case, there's something going wrong within contract configurator. I suggest checking with that mod if any recent changes were made that affect this - or if you have an incompatibility. 
If everything is checked and it's not completing, then it's not just this contract that will have problems - everything has been functional for years now without changes.

**Comment by splatpope** [comment]
Alright, I'll investigate if recent CC changes might have introduced an incompatibility. 
Can you explain how you've been doing debugging while developing your mod ? For example, I'd like to have a view on the intermediate values you calculate in your cfg (like the biome lists involved in the creation of the ScienceSubject lines)

**Comment by Morphisor244** [comment]
The core function of the mod is randomly pulling situations from available ones - this is done using Contract Configurator variables that can read the existing game info. So there's not actually much calculation at all, other than telling the contract how many situations to select.
Debugging was done using CC's own debug screen, available inside the game (alt-f10 by default). This is also the best place to check if contracts are loading properly for you: if anything shows up in red text, there are problems.
Also just a lot of trial and error, experience from previous contracts.

**Comment by splatpope** [comment]
Removing some of the mods got rid of the issue (at least for now), so I suppose it's a weird undocumented incompatibility with CC, closing the issue

**Comment by splatpope** [comment]
I removed some of the mods which looked like they impacted either the contract system or basic parts which might have confused the science subject logic, and the issues seem to be gone for now. (see the issue on the CC repo for details of which mods are implicated)

closing since this doesn't seem to be an issue with RAD, just some collateral damage with what seems to be a weird CC incompatibility with a yet unspecified mod
